import { Link } from 'react-router-dom'
import { ArrowRight, Check, Clock3, MapPin, Truck } from 'lucide-react'
import { usePageMeta } from '../hooks/usePageMeta'

const STEPS = [
  ['01', 'Valider la sélection', 'Comparez les formats et vérifiez les conseils d’utilisation avant l’ajout au panier.'],
  ['02', 'Choisir la réception', 'La solution de transport et les frais sont affichés avant la validation du paiement.'],
  ['03', 'Suivre l’expédition', 'Vous recevez les informations utiles et pouvez consulter le suivi de votre commande.'],
]

export function Delivery() {
  usePageMeta('Livraison et retours', 'Délais, zones desservies, suivi et conseils pour recevoir vos produits de nutrition équine.')
  return <div>
    <section className="bg-hunter-900 text-oat-50"><div className="mx-auto flex max-w-6xl items-end justify-between gap-8 px-4 py-16 sm:px-6 sm:py-20"><div><p className="font-body text-xs font-bold uppercase tracking-[0.2em] text-straw-400">Livraison claire, réception sereine</p><h1 className="mt-3 max-w-2xl font-display text-4xl font-semibold leading-tight sm:text-6xl">Votre commande, de la sélection à l’écurie.</h1><p className="mt-5 max-w-2xl text-base leading-relaxed text-oat-100/80">Nous vous indiquons les modalités essentielles avant le paiement, puis les informations de suivi dès l’expédition.</p></div><Truck className="hidden h-14 w-14 shrink-0 text-straw-400 sm:block" strokeWidth={1.2} /></div></section>
    <section className="mx-auto max-w-6xl px-4 py-14 sm:px-6"><div className="grid gap-5 md:grid-cols-2"><article className="border border-hunter-800/10 bg-oat-50 p-7"><Truck className="h-7 w-7 text-leather-600" /><p className="mt-6 font-body text-xs font-bold uppercase tracking-[0.16em] text-leather-700">À domicile</p><h2 className="mt-2 font-display text-2xl font-semibold text-hunter-900">Livraison en France et en Europe</h2><p className="mt-3 text-sm leading-relaxed text-ink-600">Les commandes sont préparées sous 48 heures ouvrées. Le délai de transport dépend de la destination, du poids et du transporteur sélectionné.</p><ul className="mt-5 space-y-3 text-sm text-ink-900"><li className="flex gap-2"><Check className="h-4 w-4 shrink-0 text-leather-600" />Livraison offerte en France dès 79 €</li><li className="flex gap-2"><Check className="h-4 w-4 shrink-0 text-leather-600" />Suivi communiqué dès l’expédition</li><li className="flex gap-2"><Check className="h-4 w-4 shrink-0 text-leather-600" />Colis adaptés aux formats commandés</li></ul></article><article className="border border-hunter-800/10 bg-oat-50 p-7"><MapPin className="h-7 w-7 text-leather-600" /><p className="mt-6 font-body text-xs font-bold uppercase tracking-[0.16em] text-leather-700">Besoin d’aide?</p><h2 className="mt-2 font-display text-2xl font-semibold text-hunter-900">Anticiper la réception</h2><p className="mt-3 text-sm leading-relaxed text-ink-600">Pour une commande volumineuse, un accès particulier ou une destination européenne, contactez-nous avant de valider: nous vérifierons la solution la plus adaptée.</p><Link to="/contact" className="focus-ring btn-secondary mt-6">Parler à l’équipe <ArrowRight className="h-4 w-4" /></Link></article></div></section>
    <section className="border-y border-hunter-800/10 bg-oat-200/60"><div className="mx-auto max-w-6xl px-4 py-14 sm:px-6"><p className="font-body text-xs font-bold uppercase tracking-[0.18em] text-leather-700">Le parcours en trois temps</p><div className="mt-6 grid gap-6 md:grid-cols-3">{STEPS.map(([number, title, text]) => <div key={number} className="flex gap-4"><span className="font-display text-3xl font-semibold text-leather-600">{number}</span><div><h2 className="font-display text-lg font-semibold text-hunter-900">{title}</h2><p className="mt-2 text-sm leading-relaxed text-ink-600">{text}</p></div></div>)}</div></div></section>
    <section className="mx-auto flex max-w-6xl flex-col gap-4 px-4 py-12 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div className="flex gap-3"><Clock3 className="h-6 w-6 shrink-0 text-leather-600" /><div><h2 className="font-display text-xl font-semibold text-hunter-900">Un colis reçu endommagé?</h2><p className="mt-1 text-sm text-ink-600">Notez les réserves et contactez-nous rapidement avec des photos.</p></div></div><Link to="/retours-remboursement" className="focus-ring btn-primary">Voir les retours</Link></section>
  </div>
}
